spring.application.name=backend

# MongoDB Connection
spring.data.mongodb.uri=mongodb+srv://admin:lJYWXt1tXOS2nAze@cluster0.cmnknnk.mongodb.net/
spring.data.mongodb.database=smart_campus
spring.data.mongodb.connect-timeout=2000
demo.mode.enabled=false

# Server
server.port=8082
