spring.application.name=backend

# MongoDB Connection
spring.data.mongodb.uri=mongodb+srv://admin:lJYWXt1tXOS2nAze@cluster0.cmnknnk.mongodb.net/
spring.data.mongodb.database=smart_campus
spring.data.mongodb.connect-timeout=2000
demo.mode.enabled=false

# Server
server.port=8082

# Mail Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${EMAIL_USER:weerasuriyaminidu@gmail.com}
spring.mail.password=${EMAIL_PASS:shstsshfhbauwexn}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
